import { Pool } from 'pg';
import { DatabaseConnection } from '../database/DatabaseConnection';

// ─── Helper: resolve coordinator_name → coordinator_id (findOrCreate) ──────────

async function resolveCoordinatorId(
  pool: Pool,
  coordinatorName: string | null | undefined
): Promise<string | null> {
  if (!coordinatorName) return null;
  const result = await pool.query(
    `INSERT INTO coordinators (name)
     VALUES ($1)
     ON CONFLICT (name) DO UPDATE SET name = EXCLUDED.name
     RETURNING id`,
    [coordinatorName.trim()]
  );
  return result.rows[0].id;
}

// =====================================================
// JobPostingARRepository
// =====================================================
export class JobPostingARRepository {
  private pool: Pool;
  constructor() { this.pool = DatabaseConnection.getInstance().getPool(); }

  async upsertByCaseNumber(data: {
    caseNumber: number;
    status?: string | null;
    priority?: string | null;
    isCovered?: boolean;
    coordinatorName?: string | null;
    dailyObs?: string | null;
    inferredZone?: string | null;
    country?: string;
  }): Promise<{ id: string; created: boolean }> {
    try {
      // dependency_level removed in migration 080 — now lives only in patients table
      const coordinatorId = await resolveCoordinatorId(this.pool, data.coordinatorName);

      // Lookup by case_number first (case_number is no longer unique)
      const existing = await this.pool.query<{ id: string }>(
        'SELECT id FROM job_postings WHERE case_number = $1 AND deleted_at IS NULL ORDER BY created_at DESC LIMIT 1',
        [data.caseNumber],
      );

      if (existing.rows.length > 0) {
        const jobPostingId = existing.rows[0].id;
        await this.pool.query(
          `UPDATE job_postings SET
             status           = COALESCE($2, status),
             priority         = COALESCE($3, priority),
             is_covered       = $4,
             coordinator_name = COALESCE($5, coordinator_name),
             coordinator_id   = COALESCE($6, coordinator_id),
             daily_obs        = $7,
             inferred_zone    = COALESCE($8, inferred_zone),
             updated_at       = NOW()
           WHERE id = $1`,
          [
            jobPostingId,
            data.status ?? null,
            data.priority ?? null,
            data.isCovered ?? false,
            data.coordinatorName ?? null,
            coordinatorId,
            data.dailyObs ?? null,
            data.inferredZone ?? null,
          ],
        );
        return { id: jobPostingId, created: false };
      }

      // INSERT — vacancy_number generated by SEQUENCE
      const vnResult = await this.pool.query<{ vn: string }>(
        "SELECT nextval('job_postings_vacancy_number_seq') AS vn",
      );
      const vacancyNumber = parseInt(vnResult.rows[0].vn);
      const title = `CASO ${data.caseNumber}-${vacancyNumber}`;

      const result = await this.pool.query<{ id: string }>(
        `INSERT INTO job_postings (
           vacancy_number, case_number, status, priority,
           is_covered, coordinator_name, coordinator_id,
           daily_obs, inferred_zone,
           country, title, description
         ) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12)
         RETURNING id`,
        [
          vacancyNumber,
          data.caseNumber,
          data.status ?? null,
          data.priority ?? null,
          data.isCovered ?? false,
          data.coordinatorName ?? null,
          coordinatorId,
          data.dailyObs ?? null,
          data.inferredZone ?? null,
          data.country ?? 'AR',
          title,
          `Caso operacional importado. Case #${data.caseNumber}`,
        ],
      );

      return { id: result.rows[0].id, created: true };
    } catch (err) {
      console.error(`[JobPostingRepo.upsertByCaseNumber] ERROR | caseNumber: ${data.caseNumber} | error: ${(err as Error).message}`);
      throw err;
    }
  }

  async findByCaseNumber(caseNumber: number): Promise<{ id: string } | null> {
    const result = await this.pool.query(
      'SELECT id FROM job_postings WHERE case_number = $1 AND deleted_at IS NULL ORDER BY created_at DESC LIMIT 1',
      [caseNumber]
    );
    return result.rows[0] ?? null;
  }

  /**
   * Incrementa job_postings com dados do ClickUp.
   * Lookup por case_number (pega o mais recente se houver múltiplas vacantes).
   * LLM enrichment reset via job_postings_llm_enrichment (migration 082).
   */
  async upsertFromClickUp(data: {
    caseNumber: number;
    clickupTaskId?: string | null;
    status?: string | null;
    priority?: string | null;
    title?: string | null;
    description?: string | null;
    workerProfileSought?: string | null;
    scheduleDaysHours?: string | null;
    sourceCreatedAt?: Date | null;
    sourceUpdatedAt?: Date | null;
    dueDate?: Date | null;
    searchStartDate?: Date | null;
    lastComment?: string | null;
    commentCount?: number | null;
    assignee?: string | null;
    patientId?: string | null;
    weeklyHours?: number | null;
    providersNeeded?: string | null;
    activeProviders?: number | null;
    authorizedPeriod?: Date | null;
    marketingChannel?: string | null;
    serviceAddressFormatted?: string | null;
    serviceAddressRaw?: string | null;
    country?: string;
  }): Promise<{ id: string; created: boolean }> {
    const country = data.country ?? 'AR';

    // Lookup by case_number — pega o mais recente
    const existing = await this.pool.query<{ id: string; worker_profile_sought: string | null; schedule_days_hours: string | null }>(
      `SELECT id, worker_profile_sought, schedule_days_hours
       FROM job_postings
       WHERE case_number = $1 AND deleted_at IS NULL
       ORDER BY created_at DESC LIMIT 1`,
      [data.caseNumber],
    );

    if (existing.rows.length > 0) {
      const jobPostingId = existing.rows[0].id;
      const oldWps = existing.rows[0].worker_profile_sought;
      const oldSdh = existing.rows[0].schedule_days_hours;

      await this.pool.query(
        `UPDATE job_postings SET
           status                    = $2,
           priority                  = $3,
           title                     = COALESCE(title, $4),
           description               = $5,
           worker_profile_sought     = $6,
           schedule_days_hours       = $7,
           due_date                  = $8,
           search_start_date         = $9,
           assignee                  = $10,
           patient_id                = $11,
           weekly_hours              = $12,
           providers_needed          = $13,
           active_providers          = $14,
           authorized_period         = $15,
           marketing_channel         = $16,
           service_address_formatted = $17,
           service_address_raw       = $18,
           updated_at                = NOW()
         WHERE id = $1`,
        [
          jobPostingId,
          data.status ?? null,
          data.priority ?? null,
          data.title ?? `Caso ${data.caseNumber}`,
          data.description ?? `Caso operacional importado do ClickUp. Nº ${data.caseNumber}`,
          data.workerProfileSought ?? null,
          data.scheduleDaysHours ?? null,
          data.dueDate ?? null,
          data.searchStartDate ?? null,
          data.assignee ?? null,
          data.patientId ?? null,
          data.weeklyHours ?? null,
          data.providersNeeded ?? null,
          data.activeProviders ?? null,
          data.authorizedPeriod ?? null,
          data.marketingChannel ?? null,
          data.serviceAddressFormatted ?? null,
          data.serviceAddressRaw ?? null,
        ],
      );

      await this.upsertClickUpSync(jobPostingId, data);

      const profileChanged = (data.workerProfileSought ?? null) !== oldWps
                          || (data.scheduleDaysHours ?? null) !== oldSdh;
      if (profileChanged) {
        await this.pool.query(
          `UPDATE job_postings_llm_enrichment SET llm_enriched_at = NULL WHERE job_posting_id = $1`,
          [jobPostingId],
        );
      }

      return { id: jobPostingId, created: false };
    }

    // INSERT — vacancy_number generated by SEQUENCE
    const vnResult = await this.pool.query<{ vn: string }>(
      "SELECT nextval('job_postings_vacancy_number_seq') AS vn",
    );
    const vacancyNumber = parseInt(vnResult.rows[0].vn);
    const title = data.title ?? `CASO ${data.caseNumber}-${vacancyNumber}`;

    const insertResult = await this.pool.query<{ id: string }>(
      `INSERT INTO job_postings (
         vacancy_number, case_number, country, title, description,
         status, priority,
         worker_profile_sought, schedule_days_hours,
         due_date, search_start_date, assignee,
         patient_id, weekly_hours, providers_needed, active_providers,
         authorized_period, marketing_channel,
         service_address_formatted, service_address_raw
       ) VALUES (
         $1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19,$20
       )
       RETURNING id`,
      [
        vacancyNumber,
        data.caseNumber,
        country,
        title,
        data.description ?? `Caso operacional importado do ClickUp. Nº ${data.caseNumber}`,
        data.status ?? null,
        data.priority ?? null,
        data.workerProfileSought ?? null,
        data.scheduleDaysHours ?? null,
        data.dueDate ?? null,
        data.searchStartDate ?? null,
        data.assignee ?? null,
        data.patientId ?? null,
        data.weeklyHours ?? null,
        data.providersNeeded ?? null,
        data.activeProviders ?? null,
        data.authorizedPeriod ?? null,
        data.marketingChannel ?? null,
        data.serviceAddressFormatted ?? null,
        data.serviceAddressRaw ?? null,
      ],
    );

    const jobPostingId = insertResult.rows[0].id;
    await this.upsertClickUpSync(jobPostingId, data);

    return { id: jobPostingId, created: true };
  }

  private async upsertClickUpSync(jobPostingId: string, data: {
    clickupTaskId?: string | null;
    sourceCreatedAt?: Date | null;
    sourceUpdatedAt?: Date | null;
    lastComment?: string | null;
    commentCount?: number | null;
  }): Promise<void> {
    await this.pool.query(
      `INSERT INTO job_postings_clickup_sync (
         job_posting_id, clickup_task_id, source_created_at, source_updated_at,
         last_clickup_comment, comment_count, synced_at
       ) VALUES ($1,$2,$3,$4,$5,$6,NOW())
       ON CONFLICT (job_posting_id) DO UPDATE SET
         clickup_task_id      = EXCLUDED.clickup_task_id,
         source_created_at    = EXCLUDED.source_created_at,
         source_updated_at    = EXCLUDED.source_updated_at,
         last_clickup_comment = EXCLUDED.last_clickup_comment,
         comment_count        = EXCLUDED.comment_count,
         synced_at            = NOW()`,
      [
        jobPostingId,
        data.clickupTaskId ?? null,
        data.sourceCreatedAt ?? null,
        data.sourceUpdatedAt ?? null,
        data.lastComment ?? null,
        data.commentCount ?? null,
      ],
    );
  }

  async saveCommentIfNew(params: {
    jobPostingId: string;
    commentText: string;
    commentCount: number | null;
  }): Promise<boolean> {
    if (!params.commentText.trim()) return false;

    const last = await this.pool.query<{ comment_text: string; clickup_comment_count: number | null }>(
      `SELECT comment_text, clickup_comment_count
       FROM job_posting_comments
       WHERE job_posting_id = $1
       ORDER BY captured_at DESC
       LIMIT 1`,
      [params.jobPostingId],
    );

    const lastRow = last.rows[0];
    const textChanged = !lastRow || lastRow.comment_text !== params.commentText;
    const countGrew   = params.commentCount !== null
                        && lastRow !== undefined
                        && lastRow.clickup_comment_count !== null
                        && params.commentCount > (lastRow.clickup_comment_count ?? 0);

    if (!textChanged && !countGrew) return false;

    await this.pool.query(
      `INSERT INTO job_posting_comments (job_posting_id, source, comment_text, clickup_comment_count)
       VALUES ($1, 'clickup', $2, $3)`,
      [params.jobPostingId, params.commentText, params.commentCount ?? null],
    );

    return true;
  }
}
