import { TFunction } from 'i18next';
import { VacancyRow } from '@presentation/components/features/admin/VacanciesTable';
import { SelectOption } from '@presentation/components/molecules/SelectField';

export const mockVacancies: VacancyRow[] = [
  {
    id: '1',
    initials: 'FP',
    name: 'Fabricio Paciente',
    email: 'fbertoncellascariatpaciente@gmail.com',
    caso: 'Caso 234',
    status: 'Em Processo',
    grau: 'Muito Grave',
    grauColor: 'text-[#ed0006]',
    diasAberto: '05',
    convidados: '00',
    postulados: '',
    selecionados: '',
    faltantes: '',
  },
  {
    id: '2',
    initials: 'T3',
    name: 'Test3',
    email: 'test3@test3.com',
    caso: 'Caso SN21',
    status: 'Ativo',
    grau: 'Grave',
    grauColor: 'text-[#f9a000]',
    diasAberto: '04',
    convidados: '17',
    postulados: '',
    selecionados: '',
    faltantes: '',
  },
  {
    id: '3',
    initials: '12',
    name: '123123123',
    email: 'prova@assunto.com',
    caso: 'Caso 245',
    status: 'Em Processo',
    grau: 'Moderado',
    grauColor: 'text-[#fdc405]',
    diasAberto: '07',
    convidados: '15',
    postulados: '',
    selecionados: '',
    faltantes: '',
  },
  {
    id: '4',
    initials: 'RB',
    name: 'Ruth Berdichevsky',
    email: 'berdichevskyruth@gmail.com',
    caso: 'Caso 265',
    status: 'Inativo',
    grau: 'Leve',
    grauColor: 'text-[#81c784]',
    diasAberto: '18',
    convidados: '12',
    postulados: '',
    selecionados: '',
    faltantes: '',
  },
  {
    id: '5',
    initials: 'SM',
    name: 'Santiago M. Claiman Soto',
    email: 'santsoto123@gmail.com',
    caso: 'Caso 257',
    status: 'Ativo',
    grau: 'Leve',
    grauColor: 'text-[#81c784]',
    diasAberto: '20',
    convidados: '02',
    postulados: '',
    selecionados: '',
    faltantes: '',
  },
  {
    id: '6',
    initials: 'OI',
    name: 'Ofelia Isabel',
    email: 'ofeliacaraballo@validar.com',
    caso: 'Caso 321',
    status: 'Esperando Ativação',
    grau: 'Moderado',
    grauColor: 'text-[#fdc405]',
    diasAberto: '25',
    convidados: '07',
    postulados: '',
    selecionados: '',
    faltantes: '',
  },
  {
    id: '7',
    initials: 'PV',
    name: 'Payo Victoria',
    email: 'victoriapayo@validar.com',
    caso: 'Caso 314',
    status: 'Ativo',
    grau: 'Moderado',
    grauColor: 'text-[#fdc405]',
    diasAberto: '22',
    convidados: '18',
    postulados: '',
    selecionados: '',
    faltantes: '',
  },
];

export const getStatsData = (t: TFunction) => [
  { label: t('admin.vacancies.stats.moreThan7Days'), value: '2', icon: 'clock' as const },
  { label: t('admin.vacancies.stats.moreThan24Days'), value: '20', icon: 'clock' as const },
  { label: t('admin.vacancies.stats.inSelection'), value: '44', icon: 'user-check' as const },
  { label: t('admin.vacancies.stats.totalVacancies'), value: '4,5h', icon: 'user-search' as const },
];

export const getClientOptions = (t: TFunction): SelectOption[] => [
  { value: '', label: t('admin.vacancies.clientOptions.placeholder') },
  { value: 'osde', label: t('admin.vacancies.clientOptions.osde') },
  { value: 'swiss', label: t('admin.vacancies.clientOptions.swissMedical') },
];

export const getStatusOptions = (t: TFunction): SelectOption[] => [
  { value: 'ativo', label: t('admin.vacancies.statusOptions.active') },
  { value: 'inativo', label: t('admin.vacancies.statusOptions.inactive') },
  { value: 'processo', label: t('admin.vacancies.statusOptions.inProcess') },
];
