FROM node:20-alpine

WORKDIR /tests

# Instalar dependências de sistema
RUN apk add --no-cache curl postgresql-client

# Copiar package files primeiro
COPY package*.json ./
COPY tsconfig.json ./
COPY jest.config.e2e.js ./

# Instalar dependências (incluindo dev dependencies)
RUN npm ci

# Copiar testes
COPY tests ./tests

# Comando padrão
CMD ["npm", "run", "test:e2e"]
