/**
 * public-jobs-embedded.e2e.ts
 *
 * E2E tests for JobsEmbeddedSection (legacy mode — VITE_USE_PUBLIC_JOBS_API is
 * not set in the built app, so the component fetches from /api/jobs).
 *
 * Covers:
 *   - Job cards render from mocked /api/jobs response
 *   - WhatsApp (Postularse) button is visible in legacy mode
 *   - "Ver Detalles" button is visible
 *   - No-results state renders when API returns empty list
 *   - Screenshot assertion (visual baseline)
 */

import { test, expect } from '@playwright/test';

// Worker auth — generated by auth.setup.ts
test.use({ storageState: 'e2e/.auth/profile-worker.json' });

const MOCK_JOBS_LEGACY = {
  success: true,
  count: 2,
  data: [
    {
      code: '736',
      title: '736 - Acompañante Terapéutico - Provincia de Buenos Aires - Lanús Este',
      workerType: 'acompañante terapéutico',
      provincia: 'provincia de buenos aires',
      localidad: 'lanús este',
      workerSex: 'indistinto',
      pathologies: 'trastorno disociativo, tlp',
      description: 'Descripción del caso 736.',
      service: 'domiciliario',
      daysAndHours: 'Lunes a viernes de 09:00 a 15:00 hs.',
      ageRange: '25 a 40 años',
      profile: 'AT con experiencia en salud mental.',
      whatsappLink: 'https://wa.me/5491100000000?text=CASO+736',
      detailLink: 'https://jobs.enlite.health/es/vagas/736/',
    },
    {
      code: '732',
      title: '732 - Acompañante Terapéutico - Nordelta y Puerto Madero',
      workerType: 'acompañante terapéutico',
      provincia: 'provincia de buenos aires',
      localidad: 'nordelta (tigre) y puerto madero (caba)',
      workerSex: 'mujer',
      pathologies: 'discapacidad intelectual leve',
      description: 'Descripción del caso 732.',
      service: 'traslado',
      daysAndHours: 'Lunes y jueves de 11:00 a 14:00.',
      ageRange: '20 a 45 años',
      profile: 'Profesional mujer con formación en AT.',
      whatsappLink: 'https://wa.me/5491100000000?text=CASO+732',
      detailLink: 'https://jobs.enlite.health/es/vagas/732/',
    },
  ],
};

const MOCK_WORKER_PROGRESS = {
  success: true,
  data: {
    id: 'worker-test-id',
    email: 'test@test.com',
    firstName: 'Test',
    lastName: 'Worker',
    generalInfo: null,
    serviceArea: null,
    availability: null,
  },
};

const MOCK_DOCUMENTS = {
  success: true,
  data: {
    resumeCvUrl: null,
    identityDocumentUrl: null,
    criminalRecordUrl: null,
    professionalRegistrationUrl: null,
    liabilityInsuranceUrl: null,
  },
};

const MOCK_AVAILABILITY = {
  success: true,
  data: [],
};

// ── Helper ─────────────────────────────────────────────────────────────────

async function mockWorkerApis(page: import('@playwright/test').Page): Promise<void> {
  await page.route('**/api/workers/me/progress**', route =>
    route.fulfill({
      status: 200,
      contentType: 'application/json',
      body: JSON.stringify(MOCK_WORKER_PROGRESS),
    }),
  );
  await page.route('**/api/workers/me/documents**', route =>
    route.fulfill({
      status: 200,
      contentType: 'application/json',
      body: JSON.stringify(MOCK_DOCUMENTS),
    }),
  );
  await page.route('**/api/workers/me/availability**', route =>
    route.fulfill({
      status: 200,
      contentType: 'application/json',
      body: JSON.stringify(MOCK_AVAILABILITY),
    }),
  );
  // Catch-all for any other worker API calls
  await page.route('**/api/workers/**', route => route.fulfill({
    status: 200,
    contentType: 'application/json',
    body: JSON.stringify({ success: true, data: {} }),
  }));
}

// ── Tests ──────────────────────────────────────────────────────────────────

test.describe('JobsEmbeddedSection — legacy mode', () => {
  test.setTimeout(60000);

  test('renders job cards from mocked /api/jobs', async ({ page }) => {
    await mockWorkerApis(page);
    await page.route('**/api/jobs**', route =>
      route.fulfill({
        status: 200,
        contentType: 'application/json',
        body: JSON.stringify(MOCK_JOBS_LEGACY),
      }),
    );

    await page.goto('/');
    // Wait for jobs section to appear
    await expect(page.locator('#jobs-section')).toBeVisible({ timeout: 20000 });

    // Both job cards should be visible
    await expect(page.getByText('lanús este', { exact: false }).first()).toBeVisible({ timeout: 10000 });
    await expect(page.getByText('nordelta', { exact: false }).first()).toBeVisible({ timeout: 5000 });
  });

  test('shows Postularse (WhatsApp) button in legacy mode', async ({ page }) => {
    await mockWorkerApis(page);
    await page.route('**/api/jobs**', route =>
      route.fulfill({
        status: 200,
        contentType: 'application/json',
        body: JSON.stringify(MOCK_JOBS_LEGACY),
      }),
    );

    await page.goto('/');
    await expect(page.locator('#jobs-section')).toBeVisible({ timeout: 20000 });
    await expect(page.getByText('lanús este', { exact: false }).first()).toBeVisible({ timeout: 10000 });

    // WhatsApp / Postularse button must be present (legacy mode with whatsappLink)
    const applyBtn = page.getByRole('button', { name: /postularse/i }).first();
    await expect(applyBtn).toBeVisible({ timeout: 5000 });
  });

  test('shows Ver Detalles button', async ({ page }) => {
    await mockWorkerApis(page);
    await page.route('**/api/jobs**', route =>
      route.fulfill({
        status: 200,
        contentType: 'application/json',
        body: JSON.stringify(MOCK_JOBS_LEGACY),
      }),
    );

    await page.goto('/');
    await expect(page.locator('#jobs-section')).toBeVisible({ timeout: 20000 });
    await expect(page.getByText('lanús este', { exact: false }).first()).toBeVisible({ timeout: 10000 });

    const detailBtn = page.getByRole('button', { name: /ver det/i }).first();
    await expect(detailBtn).toBeVisible({ timeout: 5000 });
  });

  test('shows no-results message when API returns empty list', async ({ page }) => {
    await mockWorkerApis(page);
    await page.route('**/api/jobs**', route =>
      route.fulfill({
        status: 200,
        contentType: 'application/json',
        body: JSON.stringify({ success: true, count: 0, data: [] }),
      }),
    );

    await page.goto('/');
    await expect(page.locator('#jobs-section')).toBeVisible({ timeout: 20000 });

    // no-results text from i18n key jobs.noResults
    await expect(
      page.getByText(/no se encontraron vacantes|nenhuma vaga encontrada/i).first(),
    ).toBeVisible({ timeout: 10000 });
  });

  test('screenshot — jobs section with legacy API data', async ({ page }) => {
    await mockWorkerApis(page);
    await page.route('**/api/jobs**', route =>
      route.fulfill({
        status: 200,
        contentType: 'application/json',
        body: JSON.stringify(MOCK_JOBS_LEGACY),
      }),
    );

    await page.goto('/');
    await expect(page.locator('#jobs-section')).toBeVisible({ timeout: 20000 });
    // Wait for at least one job card to be rendered
    await expect(page.getByText('lanús este', { exact: false }).first()).toBeVisible({ timeout: 10000 });

    await expect(page.locator('#jobs-section')).toHaveScreenshot('jobs-embedded-section.png', {
      maxDiffPixelRatio: 0.05,
    });
  });
});
