import type { PatientDetail } from '@domain/entities/PatientDetail';

export const patientDetailFixture: PatientDetail = {
  id: 'a0000000-0000-0000-0000-000000000001',
  clickupTaskId: 'TASK-001',
  firstName: 'Santiago',
  lastName: 'Claiman',
  birthDate: '1960-03-18T00:00:00Z',
  documentType: 'CPF',
  documentNumber: '123.456.789-00',
  affiliateId: null,
  sex: 'MALE',
  phoneWhatsapp: '+55 (11) 91571-1717',
  diagnosis: 'CID 6A02.5 Transtorno do espectro autista',
  dependencyLevel: 'SEVERE',
  clinicalSpecialty: 'ASD',
  clinicalSegments: null,
  serviceType: ['AT'],
  deviceType: null,
  additionalComments: 'TDAH severo',
  hasJudicialProtection: false,
  hasCud: true,
  hasConsent: true,
  insuranceInformed: null,
  insuranceVerified: null,
  cityLocality: 'São Paulo',
  province: 'SP',
  zoneNeighborhood: 'Bela Vista',
  country: 'BR',
  status: 'PENDING_ADMISSION',
  needsAttention: false,
  attentionReasons: [],
  responsibles: [
    {
      id: 'r1',
      firstName: 'Luciana',
      lastName: 'Soto',
      relationship: 'MOM',
      phone: '(11) 99852-0481',
      email: 'luciana.soto@example.com',
      documentType: 'CPF',
      documentNumber: '987.654.321-00',
      isPrimary: true,
    },
  ],
  addresses: [
    {
      id: 'addr1',
      street: 'Rua Augusta',
      number: '975',
      complement: 'Torre A, Ap. 701',
      neighborhood: 'Consolação',
      city: 'São Paulo',
      state: 'SP',
      country: 'BR',
      zipCode: '01310-100',
      fullAddress: 'Rua Augusta, 975 - São Paulo/SP. Torre A, Ap. 701',
    },
  ],
  professionals: [
    {
      id: 'prof1',
      fullName: 'Dr. João Alves Pereira',
      phone: '+55 (11) 97580-1332',
      email: 'joao.pereira@clinic.com',
      specialty: 'Psicólogo',
    },
  ],
  createdAt: '2025-01-10T12:00:00Z',
  updatedAt: '2026-04-20T09:30:00Z',
};

export const patientDetailMinimal: PatientDetail = {
  id: 'b0000000-0000-0000-0000-000000000002',
  clickupTaskId: 'TASK-002',
  firstName: null,
  lastName: null,
  birthDate: null,
  documentType: null,
  documentNumber: null,
  affiliateId: null,
  sex: null,
  phoneWhatsapp: null,
  diagnosis: null,
  dependencyLevel: null,
  clinicalSpecialty: null,
  clinicalSegments: null,
  serviceType: null,
  deviceType: null,
  additionalComments: null,
  hasJudicialProtection: null,
  hasCud: null,
  hasConsent: null,
  insuranceInformed: null,
  insuranceVerified: null,
  cityLocality: null,
  province: null,
  zoneNeighborhood: null,
  country: 'AR',
  status: null,
  needsAttention: false,
  attentionReasons: [],
  responsibles: [],
  addresses: [],
  professionals: [],
  createdAt: '2026-01-01T00:00:00Z',
  updatedAt: '2026-01-01T00:00:00Z',
};
